server:
  port: 9090
spring:
  kafka:
    bootstrap-servers: 10.255.15.126:9092,10.255.15.125:9092,10.255.15.124:9092
    consumer:
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      auto-offset-reset: earliest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3  #  重试次数
      acks: 1
      batch-size: 323840
      buffer-memory: 33554432
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    my-topic: test-topic

