server:
  port: 9091
spring:
  kafka:
    bootstrap-servers: 10.255.15.126:9092,10.255.15.125:9092,10.255.15.124:9092
    consumer:
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      auto-offset-reset: earliest
      group-id: test_group
      enable-auto-commit: true
      auto-commit-interval: 2000


kafka:
  topic:
    my-topic: test-topic

